version: "3"

services:
  db:
    image: mariadb:10.7.3
    restart: unless-stopped
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_DATABASE}
    volumes:
      - easyshortener-db-data:/var/lib/mysql

  easyshortener:
    image: ghcr.io/easypanel-community/easyshortener
    container_name: easyshortner
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - EASYSHORTENER_ALLOW_REGISTRATION=true
      - EASYSHORTENER_INSTALLATION_ENV=docker
    ports:
      - "8080:80"
    volumes:
      - ./.env:/var/www/html/.env

volumes:
  easyshortener-db-data:
